spring.application.name=cineapi

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/cine_api?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=pa55word
spring.jpa.hibernate.ddl-auto=update

